{"name": "test_except_case[case2]", "status": "passed", "description": "登录异常", "attachments": [{"name": "log", "source": "81ebe1df-c04e-4c54-816b-f2fe7cefabbd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'mobile': '1868472055@', 'pwd': 'python', 'expected': '请输入正确的手机号'}"}], "start": 1590498338355, "stop": 1590498340310, "uuid": "5b579703-3b58-40f2-ba38-23b937008d5f", "historyId": "c19513bf540429d36ea1db51a2488fed", "testCaseId": "b254529e103211879e53220ccf37bfcb", "fullName": "testcases.test_login.TestLogin#test_except_case", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "wo"}, {"name": "thread", "value": "8788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}