{"name": "test_except_case[case2]", "status": "passed", "description": "登录异常", "attachments": [{"name": "log", "source": "ad61bf0c-2d35-4d56-8956-2b893d2c2729-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'mobile': '1868472055@', 'pwd': 'python', 'expected': '请输入正确的手机号'}"}], "start": 1590503409291, "stop": 1590503409991, "uuid": "38c71746-e05e-4fe4-8374-1840a418b779", "historyId": "c19513bf540429d36ea1db51a2488fed", "testCaseId": "b254529e103211879e53220ccf37bfcb", "fullName": "testcases.test_login.TestLogin#test_except_case", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "wo"}, {"name": "thread", "value": "7072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}