{"name": "test_except_case[case2]", "status": "passed", "description": "登录异常", "attachments": [{"name": "log", "source": "af1e8ef6-1c0b-45ce-b9ff-2ba649ed9766-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'mobile': '1868472055@', 'pwd': 'python', 'expected': '请输入正确的手机号'}"}], "start": 1590504059042, "stop": 1590504059664, "uuid": "e3324779-dfb9-42a2-9f82-06e038e85015", "historyId": "c19513bf540429d36ea1db51a2488fed", "testCaseId": "b254529e103211879e53220ccf37bfcb", "fullName": "testcases.test_login.TestLogin#test_except_case", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "wo"}, {"name": "thread", "value": "4740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}