{"name": "test_login_alert[case1]", "status": "passed", "description": "异常用例，错误信息弹窗提示", "attachments": [{"name": "log", "source": "9ec05ddd-2eb1-477e-9744-e07f700863a1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'mobile': '18684720553', 'pwd': 'python888', 'expected': '帐号或密码错误!'}"}], "start": 1590504060619, "stop": 1590504061465, "uuid": "c4859d01-dfa8-42e7-a20d-1c4696051924", "historyId": "65ff18146948f2658303e7b68ac96de1", "testCaseId": "8b653efc132135221fc57baf686031ef", "fullName": "testcases.test_login.TestLogin#test_login_alert", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "wo"}, {"name": "thread", "value": "4740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}