{"name": "test_except_case[case2]", "status": "passed", "description": "登录异常", "attachments": [{"name": "log", "source": "b8fcb4f2-7241-4e39-865c-c43021cadfec-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'mobile': '1868472055@', 'pwd': 'python', 'expected': '请输入正确的手机号'}"}], "start": 1590758317017, "stop": 1590758317719, "uuid": "36834035-22f9-49fb-833a-d83785f02443", "historyId": "c19513bf540429d36ea1db51a2488fed", "testCaseId": "b254529e103211879e53220ccf37bfcb", "fullName": "testcases.test_login.TestLogin#test_except_case", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "wo"}, {"name": "thread", "value": "936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}